import NavLinks from '@/components/NavLinks'
import '../(protected)/styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <>
        <NavLinks />
        <body>{children}</body>
      </>
    </html>
  )
}
