import NavLinks from '@/components/NavLinks'
import 'src/app/(frontend)/styles.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
