import Footer from '@/components/Footer'
import NavLinks from '@/components/NavLinks'

import 'src/app/(frontend)/styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  )
}
